<?php

namespace Database\Seeders;

use App\Models\Ingredients;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ingredients = [
            'Bawang Merah',
            'Bawang Putih',
            'Kunyit',
            'Jahe',
            'Kemiri',
            'Ketumbar',
            'Kencur',
            'Serai',
            'Lada',
            'Merica',
            'Kecap',
            'Garam',
            'Gula',
            'Minyak Goreng',
            'Minyak Sayur',
            'Minyak Kelapa',
            'Minyak Zaitun',
            'Minyak Wijen',
            'Minyak Jagung',
            'Minyak Biji Bunga Matahari',
            'Telur Ayam',
            'Telur Bebek',
            'Telur Puyuh',
            'Daging Ayam',
            'Daging Sapi',
            'Daging Kambing',
            'Daging Bebek',
            'Ikan Tuna',
            'Ikan Salmon',
            'Ikan Tongkol',
            'Ikan Lele',
            'Ikan Gurame',
            'Ikan Bandeng',
            'Udang',
            'Cumi-cumi',
            'Kepiting',
            'Kerang',
            'Lobster',
            'Tempe',
            'Tahu',
            'Susu Sapi',
            'Susu Kambing',
            'Santan',
            'Tepung Terigu',
            'Tepung Beras',
            'Tepung Jagung',
            'Tepung Sagu',
            'Tepung Tapioka',
            'Tepung Kentang',
            'Tepung Maizena',
            'Nasi',
            'Beras Putih',
            'Beras Merah',
            'Beras Hitam',
            'Beras Coklat',
            'Mie Telur',
            'Mie Kuning',
            'Mie Instan',
            'Pasta',
            'Spaghetti',
            'Fusilli',
            'Penne',
            'Lasagna',
            'Ravioli',
            'Kentang',
            'Ubi Jalar',
            'Singkong',
            'Jagung',
            'Sawi Hijau',
            'Sawi Putih',
            'Bayam',
            'Kangkung',
            'Daun Pepaya',
            'Daun Singkong',
            'Kol',
            'Brokoli',
            'Kembang Kol',
            'Buncis',
            'Wortel',
            'Labu Siam',
            'Labu Kuning',
            'Timun',
            'Mentimun',
            'Terong',
            'Kacang Panjang',
            'Kacang Merah',
            'Kacang Hijau',
            'Kacang Tanah',
            'Kacang Mede',
            'Almond',
            'Hazelnut',
            'Kenari',
            'Kismis',
            'Kurma',
            'Aprikot Kering',
            'Plum Kering',
            'Buah Zaitun',
            'Buah Naga',
            'Mangga',
            'Pisang',
            'Jeruk',
            'Apel',
            'Anggur',
            'Kiwi',
            'Leci',
            'Delima',
            'Semangka',
            'Melon',
            'Pepaya',
            'Jambu Biji',
            'Jambu Air',
            'Nangka',
            'Durian',
            'Sirsak',
            'Salak',
            'Manggis',
            'Rambutan',
            'Kelengkeng',
            'Ciplukan',
            'Tomat',
            'Cabe Merah',
            'Cabe Rawit',
            'Cabe Hijau',
            'Paprika',
            'Jahe Merah',
            'Kayu Manis',
            'Pala',
            'Kapulaga',
            'Cengkeh',
            'Jinten',
            'Lada Hitam',
            'Lada Putih',
            'Lengkuas',
            'Daun Salam',
            'Daun Jeruk',
            'Daun Pandan',
            'Daun Ketumbar',
            'Daun Seledri',
            'Daun Bawang',
            'Daun Kari',
            'Daun Kemangi',
            'Buah Kemukus',
            'Asam Jawa',
            'Asam Kandis',
            'Asam Gelugur',
            'Asam Sunti',
            'Daun Kelor',
            'Buah Melinjo',
            'Buah Jengkol',
            'Buah Pete',
            'Temulawak',
            'Rosella',
            'Sambal Terasi',
            'Sambal Ulek',
            'Sambal Kacang',
            'Sambal Matah',
            'Sambal Kecap',
            'Sambal Balado',
            'Sambal Goreng',
            'Sambal Tomat',
            'Sambal Terong',
            'Sambal Ijo',
            'Sambal Bawang',
            'Acar Timun',
            'Acar Wortel',
            'Acar Nanas',
            'Acar Cabai',
            'Sayur Lodeh',
            'Sayur Asem',
            'Sayur Sop',
            'Sayur Bening',
            'Soto Ayam',
            'Soto Daging',
            'Soto Betawi',
            'Soto Lamongan',
            'Soto Madura',
            'Soto Padang',
            'Sate Ayam',
            'Sate Kambing',
            'Sate Padang',
            'Sate Lilit',
            'Sate Maranggi',
            'Sate Usus',
            'Sate Jeroan',
            'Gulai Ayam',
            'Gulai Kambing',
            'Gulai Sapi',
            'Gulai Ikan',
            'Rendang Daging',
            'Rendang Ayam',
            'Rendang Jengkol',
            'Rendang Sapi',
            'Rendang Kambing',
            'Ayam Goreng',
            'Ayam Bakar',
            'Ayam Penyet',
            'Ayam Rica-Rica',
            'Ayam Betutu',
            'Ayam Taliwang',
            'Ayam Geprek',
            'Ayam Gulai',
            'Dendeng Balado',
            'Dendeng Batokok',
            'Sambal Goreng Kentang',
            'Sambal Goreng Ati',
            'Sambal Goreng Tempe',
            'Sambal Goreng Tahu',
            'Sambal Goreng Udang',
            'Sambal Goreng Petai',
            'Sambal Goreng Kerang',
            'Sambal Goreng Ikan',
            'Tumis Kangkung',
            'Tumis Bayam',
            'Tumis Daun Singkong',
            'Tumis Buncis',
            'Tumis Kacang Panjang',
            'Tumis Jamur',
            'Tumis Toge',
            'Tumis Wortel',
            'Tumis Terong',
            'Tumis Pare',
            'Tumis Tempe',
            'Tumis Tahu',
            'Nasi Goreng',
            'Nasi Uduk',
            'Nasi Liwet',
            'Nasi Kuning',
            'Nasi Kebuli',
            'Nasi Lemak',
            'Nasi Timbel',
            'Nasi Bakar',
            'Lontong Sayur',
            'Ketupat Sayur',
            'Opor Ayam',
            'Opor Telur',
            'Opor Tahu',
            'Opor Tempe',
            'Opor Daging',
            'Bakso Sapi',
            'Bakso Ayam',
            'Bakso Ikan',
            'Bakso Udang',
            'Bakso Tahu',
            'Bakso Tempe',
            'Bakso Tahu Goreng',
            'Bakwan Jagung',
            'Bakwan Sayur',
            'Bakwan Udang',
            'Bakwan Tahu',
            'Pempek Palembang',
            'Siomay Bandung',
            'Bubur Ayam',
            'Bubur Kacang Hijau',
            'Bubur Sumsum',
            'Bubur Manado',
            'Bubur Pedas',
            'Tahu Bulat',
            'Tahu Isi',
            'Tempe Goreng',
            'Tempe Mendoan',
            'Perkedel Kentang',
            'Perkedel Jagung',
            'Perkedel Tahu',
            'Perkedel Tempe',
            'Gado-Gado',
            'Pecel',
            'Karedok',
            'Lotek',
            'Lalapan',
            'Kerupuk Udang',
            'Kerupuk Ikan',
            'Kerupuk Kulit',
            'Kerupuk Mie',
            'Emping Melinjo',
            'Keripik Tempe',
            'Keripik Singkong',
            'Keripik Kentang',
            'Keripik Pisang',
            'Rujak Buah',
            'Rujak Cingur',
            'Rujak Kangkung',
            'Es Campur',
            'Es Teler',
            'Es Doger',
            'Es Pisang Ijo',
            'Es Cendol',
            'Es Kacang Merah',
            'Es Kopyor',
            'Es Kelapa Muda',
            'Es Buah',
        ];

        foreach ($ingredients as $ingredient) {
            Ingredients::create(['name' => $ingredient]);
        }
        
    }
}
